"use strict";
const KEY="guerz-visibility-quality-desk-v1";const $=s=>document.querySelector(s);const $$=s=>[...document.querySelectorAll(s)];const checks=$$(".check-row input[type=checkbox]");const fields=$$("[data-field]");const lanes=$$(".review-lane");const toast=$("#toast");let timer,focused=false;
function say(m){clearTimeout(timer);toast.textContent=m;toast.classList.add("show");timer=setTimeout(()=>toast.classList.remove("show"),2800)}
function read(){try{return JSON.parse(localStorage.getItem(KEY))||{}}catch(e){console.warn(e);return{}}}
function save(){const state={checks:Object.fromEntries(checks.map(x=>[x.id,x.checked])),fields:Object.fromEntries(fields.map(x=>[x.dataset.field,x.value])),theme:document.documentElement.dataset.theme};try{localStorage.setItem(KEY,JSON.stringify(state))}catch(e){console.warn(e);say("Could not save locally—export the desk log.")}}
function render(){const done=checks.filter(x=>x.checked).length,total=checks.length,p=total?Math.round(done/total*100):0;$("#score-number").textContent=p+"%";$("#progress-text").textContent=`${done} of ${total} desk checks complete`;$("#progress-fill").style.width=p+"%";$("#progress-meter").setAttribute("aria-valuenow",p)}
function restore(){const s=read();checks.forEach(x=>x.checked=!!s.checks?.[x.id]);fields.forEach(x=>x.value=s.fields?.[x.dataset.field]??x.value);document.documentElement.dataset.theme=s.theme==="dark"?"dark":"light";render()}
function next(){const visible=checks.filter(x=>!x.checked&&!x.closest(".review-lane").hidden);const box=visible[0]||checks.find(x=>!x.checked);if(!box){$("#next-task").textContent="Desk cleared. Log the release, close the tabs, and let the site exist.";say("Desk clear. Put the red pen down.");return}const lane=box.closest(".review-lane");lane.querySelectorAll("details").forEach(d=>d.open=true);$("#next-task").innerHTML=`<strong>${lane.querySelector("h2").textContent}</strong><br>${box.parentElement.querySelector("strong").textContent}`;lane.scrollIntoView({behavior:"smooth",block:"center"});setTimeout(()=>box.focus({preventScroll:true}),420);say("One next check selected.")}
function filter(){const v=$("#lane-filter").value;lanes.forEach(l=>l.hidden=v!=="all"&&l.dataset.lane!==v);focused=false;document.body.classList.remove("focused");lanes.forEach(l=>l.classList.remove("focus-lane"));$("#focus-toggle").setAttribute("aria-pressed","false");$("#focus-toggle").textContent="Enter focus review";say(v==="all"?"Showing every desk lane.":"Desk lane filtered.")}
function focus(){focused=!focused;const visible=lanes.filter(l=>!l.hidden);const target=visible.find(l=>l.querySelector("input[type=checkbox]:not(:checked)"))||visible[0];lanes.forEach(l=>l.classList.toggle("focus-lane",focused&&l===target));document.body.classList.toggle("focused",focused);$("#focus-toggle").setAttribute("aria-pressed",focused);$("#focus-toggle").textContent=focused?"Exit focus review":"Enter focus review";if(focused&&target)target.scrollIntoView({behavior:"smooth",block:"start"});say(focused?"One desk lane. Everything else can wait.":"Full desk restored.")}
function exportLog(){const rows=fields.map(f=>`- ${f.dataset.field}: ${String(f.value).replace(/\n/g," ")||"—"}`);const list=checks.map(c=>`- [${c.checked?"x":" "}] ${c.parentElement.querySelector("strong").textContent}`);const text=["---","title: Guerz Visibility & Quality Control Desk",`updated: ${new Date().toISOString().slice(0,10)}`,"---","","# Guerz Visibility & Quality Control Desk","","## Checks",...list,"","## Desk records",...rows,"","## Liner note","Original desk writing and design: Guerz. Third-party platform materials remain subject to their owners’ terms.",""].join("\n");const url=URL.createObjectURL(new Blob([text],{type:"text/markdown;charset=utf-8"}));const a=document.createElement("a");a.href=url;a.download="guerz-visibility-quality-desk-log.md";document.body.append(a);a.click();a.remove();setTimeout(()=>URL.revokeObjectURL(url),1000);say("Desk log exported for Obsidian.")}
checks.forEach(c=>c.addEventListener("change",()=>{save();render()}));fields.forEach(f=>f.addEventListener("input",save));$("#pick-next-task").onclick=next;$("#export-progress").onclick=exportLog;$("#lane-filter").onchange=filter;$("#focus-toggle").onclick=focus;$("#open-all-details").onclick=()=>$$('details').forEach(d=>d.open=true);$("#close-all-details").onclick=()=>$$('details').forEach(d=>d.open=false);$("#theme-toggle").onclick=()=>{document.documentElement.dataset.theme=document.documentElement.dataset.theme==="dark"?"light":"dark";save();say("Theme switched.")};$("#reset-progress").onclick=()=>{if(!confirm("Reset all local desk checkmarks and notes? Export first if you need a record."))return;localStorage.removeItem(KEY);checks.forEach(c=>c.checked=false);fields.forEach(f=>{if(!["meta-home-url","meta-project-url","lh-home-url","lh-project-url"].includes(f.dataset.field))f.value=""});render();say("Local desk reset.")};restore();